version: '3'
services:
  blockchain:
    container_name: blockchain
    image: blockchain:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - BLOCKCHAIN_IP=0.0.0.0
      - WRITER_PORT=12345
      - READER_PORT=12346
      - api_LISTEN_CONNECTIONS=2
    networks:
      - blockchain_system

  api:
    container_name: api
    image: api:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - BLOCKCHAIN_IP=blockchain
      - WRITER_PORT=12345
      - READER_PORT=12346
      - API_PORT=5000
      - N_MINERS=5
      - api_LISTEN_CONNECTIONS=2
    ports:
      - "5000:5000"
    networks:
      - blockchain_system
    depends_on: 
      - blockchain
  
networks:
  blockchain_system:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24