import struct

TIMESTAMP_FORMAT = "%m-%d-%Y, %H:%M:%S"

MAX_ENTRIES = 256

CHUNK_SIZE = 65536

MAX_BLOCK_SIZE = CHUNK_SIZE * MAX_ENTRIES

POST_CHUNK = "POST_CHUNK"

GET_STATS = "GET_STATS"

GET_BLOCK = "GET_BLOCK"

GET_BLOCKS = "GET_BLOCKS"

ACK_SCHEME = struct.Struct('?')

TIMEOUT_WAITING_MESSAGE = 2